services:

  db:
    build: './mysql'
    container_name: mysql_c
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - ./mysql/dbData:/var/lib/mysql

  back:
    build: './back'
    container_name: backend_c
    env_file:
      - ./.env
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
    ports:
      - "${BACKEND_PORT}:80"
    volumes:
      - ./back:/var/www/html

  front:
    build: './front'
    container_name: front_c
    env_file:
      - ./.env
    ports:
      - "${FRONTEND_PORT}:80"
    volumes:
      - ./front:/var/www/html

  adminer:
    image: adminer
    container_name: adminer_c
    ports:
      - "8080:8080"

volumes:
  dbData: